//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlakcilik.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gayrimenkul
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gayrimenkul()
        {
            this.Ilan = new HashSet<Ilan>();
        }
    
        public int Id { get; set; }
        public Nullable<int> OdaSayisi { get; set; }
        public string Adres { get; set; }
        public Nullable<System.DateTime> InsaatTarih { get; set; }
        public Nullable<int> KatSayisi { get; set; }
        public string Isitma { get; set; }
        public Nullable<bool> Esya { get; set; }
        public Nullable<bool> Boya { get; set; }
        public Nullable<bool> Havuz { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ilan> Ilan { get; set; }
    }
}
